apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ template "elasticsearch.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  elasticsearch_custom.yml: |-

    discovery:
      zen:
        ping.unicast.hosts: {{ template "elasticsearch.discovery.fullname" . }}
        minimum_master_nodes: 2

{{- if .Values.config }}
{{ toYaml .Values.config | indent 4 }}
{{- end }}
