name: nginx-ingress-controller
version: 3.1.2
appVersion: 0.21.0
description: Chart for the nginx Ingress controller
keywords:
- ingress
- nginx
- http
- web
- www
- reverse proxy
home: https://github.com/kubernetes/ingress-nginx
icon: https://bitnami.com/assets/stacks/nginx-ingress-controller/img/nginx-ingress-controller-stack-220x234.png
sources:
- https://github.com/bitnami/bitnami-docker-nginx-ingress-controller
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
