{{- if .Values.externaldb.broker.serviceInstanceName }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "mean.mongodb.fullname" . }}-binding
  labels:
    app: {{ template "mean.name" . }}
    chart: {{ template "mean.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ .Values.externaldb.broker.serviceInstanceName }}
  secretName: {{ template "mean.secretName" . }}
{{- end }}
