resource_type: Gestalt::Resource::ApiEndpoint
name: /url-redirect
description: Sample NodeJS Lambda
properties:
  resource: /url-redirect
  methods:
  - GET
  plugins:
    rateLimit:
      enabled: false
      perMinute: 60
    gestaltSecurity:
      enabled: false
      users: []
      groups: []
  synchronous: true
  is_http_aware: true
  implementation_type: lambda
  implementation_id: '#{Lambda url-redirect-lambda}'
  hosts: []
context:
  api:
    id: '#{Api #{Config api}}'
